**What is NumPy?**

NumPy is a Python library used for working with arrays.

**Why use NumPy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

**Numpy arrays are faster than Python lists because they:**

*   Store data contiguously in memory with a uniform data type, allowing for efficient access and processling.
*   Are implemented in highly optimized C and Fortran, enabling vectorized operations that avoid Python's slower interpreted loops.
*   Have less memory overhead per element due to their fixed data type and contiguous storage.



In [36]:
# Import Numpy
import numpy 

print("numpy version is: "+ numpy.__version__)

numpy version is: 2.3.2


NumPy is usually imported under the **np** alias

In [37]:
import numpy as np

print(np)

<module 'numpy' from 'c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\__init__.py'>


To create an **ndarray**, we can pass a list, tuple or any array-like objet into the **array()** method, and it will be converted into ndarray.

In [38]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr)
print(type(arr))

arr= arr*2
print(arr)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [39]:
# 0D array

import numpy as np

array = np.array(2)
print("This is a " + str(array.ndim) + "D array")

This is a 0D array


In [40]:
# 1D array

import numpy as np

array = np.array(['a','b','c'])
print("This is a " + str(array.ndim) + "D array")

This is a 1D array


In [41]:
# 2D Arrays
import numpy as np

array = np.array([['a','b','c'], ['d','e','f'],['g','h','i']])
print("This is a " + str(array.ndim) + "D array")

This is a 2D array


In [42]:
# 3D Arrays
import numpy as np

array = np.array([[['a','b','c'], ['d','e','f'],['g','h','i']],
                  [['j','k','l'], ['m','n','o'],['p','q','r']],
                  [['s','t','u'], ['v','w','x'],['y','z','a']]])
print("This is a " + str(array.ndim) + "D array")

This is a 3D array


In [43]:
# Check Number of Dimensions
import numpy as np

array= np.array(['a','b','c'])

print(array.ndim)

1


In [44]:
#Shape in array
#(3,3,3) depth-row-clumn
import numpy as np

array = np.array([[['a','b','c'], ['d','e','f'],['g','h','i']],
                  [['j','k','l'], ['m','n','o'],['p','q','r']],
                  [['s','t','u'], ['v','w','x'],['y','z','a']]])
print(array.shape)

(3, 3, 3)


Array indexing is the same as accessing an array element

In [45]:
import numpy as np

array = np.array([[['a','b','c'], ['d','e','f'],['g','h','i']],
                  [['j','k','l'], ['m','n','o'],['p','q','r']],
                  [['s','t','u'], ['v','w','x'],['y','z','a']]])
print(array[0,0,0])
print(array [0,1,0])

name= array[0,2,2] +array[2,0,0] + array[1,2,2]+array[0,0,0]+array[0,1,2]+array[0,2,2]+array[1,0,2]
print(name)

a
d
israfil


In [67]:
#Slicing

import numpy as np

array =np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

#array[start:end:step]

print(array[0:4:3])

#to reverse
print ('Array reverse is: ')
print(array[::-1])

#clumn wise

print ("This will give us clumn 0 "+ str(array[:,0]))
print ("This will give us clumn 1 "+ str(array[:,1]))
print ("This will give us clumn 3 "+ str(array[:,2]))
print ("This will give us  last clumn "+ str(array[:,-1]))

print ("This will give us first 3 index clumn  \n"+ str(array[:,0:3]))



[[ 1  2  3  4]
 [13 14 15 16]]
Array reverse is: 
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
This will give us clumn 0 [ 1  5  9 13]
This will give us clumn 1 [ 2  6 10 14]
This will give us clumn 3 [ 3  7 11 15]
This will give us  last clumn [ 4  8 12 16]
This will give us first 3 index clumn  
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [51]:
# Negative Indexing

import numpy as np

array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

print(array[-1])


[13 14 15 16]


Arithmetic

In [ ]:
#scalar arithmetic
import numpy as np


array =np.array([1,2,3])
print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array**5)



[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [73]:
#Vectrized math funcs

import numpy as np

array=np.array([1.01,2.5,3.99])

print(np.sqrt(array))
print((np.round(array)))

print((np.ceil(array)))

print(np.pi)


radii = np.array([1,2,3])

print(np.pi * radii **2)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[2. 3. 4.]
3.141592653589793
[ 3.14159265 12.56637061 28.27433388]


In [77]:
#Element- Wise arithmetic

import numpy as np 

arra1= np.array([1,2,3])
arra2= np.array([4,5,6])

print(arra1+arra2)
print(arra1-arra2)
print(arra1*arra2)
print(arra1/arra2)
print(arra1**arra2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [78]:
#Comparison operators 

import numpy as np

scores = np.array([92,78,55,89])

print(scores>60)

[ True  True False  True]
